import { createOpeningInventory, listLocations, listLots, listProducts } from "../js/api-smooth1.js?v=open4";
import { formToObject, notice } from "../js/utils.js";
export async function render(ctx) {
  ctx.setTitle("Opening Inventory", "Add products to available spaces");
  const [locations, products, lots] = await Promise.all([listLocations(), listProducts(), listLots()]);
  const spaces = locations.filter(l => String(l.current_status || "AVAILABLE").toUpperCase() === "AVAILABLE");
  ctx.view.innerHTML = `<section class="panel"><div class="panel-header"><div><h2>Add opening stock</h2><p class="muted">Pick existing products and lots to reuse details, or type new ones.</p></div></div><form id="openingForm" class="form-grid"><div class="field"><label>Available space</label><select name="location_id" required>${spaces.map(l=>`<option value="${l.location_id}">${l.location_id}</option>`).join("")}</select></div><div class="field"><label>Product name</label><input id="openingProduct" name="product_name" list="products" required><datalist id="products">${products.map(p=>`<option value="${p.product_name}"></option>`).join("")}</datalist></div><div class="field"><label>Previous lot (optional)</label><select id="openingLot" name="previous_lot"><option value="">New lot / type details</option></select></div><div class="field"><label>Lot #</label><input name="supplier_lot_number"></div><div class="field"><label>Amount</label><input name="qty" type="number" step=".01" required></div><div class="field"><label>Purchase unit</label><input name="purchase_unit" required></div><div class="field"><label>Weight per unit (LB)</label><input name="purchase_unit_weight" type="number" step=".01" required></div><div class="field"><label>Perishability (days)</label><input name="perishability_days" type="number" value="0"></div><div class="field"><label>Category</label><input name="product_category" value="General"></div><div class="field full"><button class="btn">Add opening inventory</button></div></form></section>`;
  const form=document.getElementById("openingForm"), productInput=document.getElementById("openingProduct"), lotSelect=document.getElementById("openingLot");
  const refreshLots=()=>{const p=products.find(x=>x.product_name.toLowerCase()===productInput.value.trim().toLowerCase());const options=lots.filter(l=>!p||l.product_id===p.product_id);lotSelect.innerHTML=`<option value="">New lot / type details</option>${options.map(l=>`<option value="${l.internal_lot_id}">${l.supplier_lot_number||l.internal_lot_id} (${l.purchase_unit_type||"unit"})</option>`).join("")}`;if(p){form.elements.perishability_days.value=p.perishability_days||0;form.elements.product_category.value=p.product_category||"General";}};
  productInput.addEventListener("change",refreshLots); productInput.addEventListener("input",refreshLots);
  lotSelect.addEventListener("change",()=>{const l=lots.find(x=>x.internal_lot_id===lotSelect.value);if(!l)return;form.elements.supplier_lot_number.value=l.supplier_lot_number||"";form.elements.purchase_unit.value=l.purchase_unit_type||"";form.elements.purchase_unit_weight.value=(Number(l.original_qty||0)/Number(l.purchase_qty_received||1))||"";});
  form.addEventListener("submit",async e=>{e.preventDefault();try{const r=await createOpeningInventory(ctx.user,formToObject(form));notice(`${r.product.product_name} added.`);await render(ctx);}catch(err){notice(err.message);}});
}
